Overlay index fetch issue
zen-fs/core pull request #82
Opened 2024-07-01 06:33 UTC by terryluan12

Should resolve #78 and one of the additional bugs mentioned in #80

2024-07-01 06:42 UTC, terryluan12 commented
As mentioned in #80, there were issues when initializing the `Stat` objects. Looking further into it, I found that the `dirEntries` was called to get the directory entries. However, it simply iterates through the keys of the `Index`. Since the `Index` object is in the process of being created when this is called, not all keys which would otherwise be in the final `Index` object are there when it's called.

I also found the bug which caused the double unlocking bug. This occurs if the program locks a path 3 times. 
On it's first lock, it would creates a Promise 'A'. Then when it locks a second time, it `awaits` Promise 'A'. Finally on it's third time, it would also `await` Promise 'A'. When the program unlocks the lock (resolving Promise 'A'), both threads which are awaiting 'A' start running at the same time, which causes the bug.

2024-07-01 15:55 UTC, james-pre commented
@terryluan12 Some changes have been made. Primarily, the `Mutex` logic has been folded into `LockedFS`. Please consult the release notes for v0.14.0.

2024-07-01 20:02 UTC, terryluan12 commented
Ah, didn't even notice it, thanks for the heads up! I just merged + re-added the changes

2024-07-02 13:58 UTC, james-pre requested changes

2024-07-02 13:58 UTC, james-pre commented on src/backends/index/index.ts
These changes relate to the issue you mentioned in #80, please refer to my other comment.

2024-07-02 13:58 UTC, james-pre commented on src/backends/locked.ts
> +	private locks: Map<string, [MutexLock]> = new Map();
This is a tuple with a single `MutexLock`. Do you mean an array, `MutexLock[]`?

2024-07-02 13:58 UTC, james-pre commented on src/backends/locked.ts
> -			await this.locks.get(path)!.promise;
1. This is not a promise. `await`ing the lock has no effect and is a bug.
2. Please inline: `await this.locks.get(path)!.at(-1).promise`

2024-07-02 13:58 UTC, james-pre commented on src/backends/locked.ts
> +		const res = this.locks.get(path)!.shift();
Again, please inline: `this.locks.get(path)!.shift().resolve();`

2024-07-02 13:58 UTC, james-pre commented on src/backends/locked.ts
> +		return this.locks.has(path) && this.locks.get(path)!.length > 0;
Can be simplified: `return !!this.locks.get(path)?.length`

2024-07-02 13:59 UTC, james-pre commented
> As mentioned in #80, there were issues when initializing the `Stat` objects. Looking further into it, I found that the `dirEntries` was called to get the directory entries. However, it simply iterates through the keys of the `Index`. Since the `Index` object is in the process of being created when this is called, not all keys which would otherwise be in the final `Index` object are there when it's called.

This should have been resolved in https://github.com/zen-fs/core/commit/ec86a6aacfcc36d0960f2a1280b88d21bce8bc92. Please let me know if the issue still happens- you will need to run `make-index` again. I am again using a regex since it is relatively slow. If one was to have 10,000 files for example, creating a new regex for each one slows things down.

2024-07-20 19:14 UTC, james-pre commented
@terryluan12 Any updates on this?

2024-08-18 19:20 UTC, james-pre commented
@terryluan12 Any updates on this?

2024-08-29 03:48 UTC, terryluan12 commented
Hi @james-pre, so sorrry about the lack of update! Got busy with some real life stuff, and didn't see the comments. Just got a replacement for my previous laptop, and will get to work on zen-fs, and finish up this issue ASAP

2024-09-06 06:21 UTC, terryluan12 commented
Hey @james-pre, I've been taking a look at the double unlocking issue, and I've gotten an idea of why it's bugging. Specifically, it occurs when you have two processes waiting on a locked promise. Once the promise resolves, both processes will continue at the same time. Thus they'll both call addLock, and one promise will override the others, causing the weird double unlocking. Thinking about it, I think one possible solution is to implement a queuing system. What are your thoughts?

2024-09-06 16:35 UTC, james-pre commented
@terryluan12,

Thanks for your dedication to this.

My thinking is that we should try to avoid a queue system.

It *should* work like this:
- call asynchronous methods `a` and `b` on the same path without using `await`,
	- i.e.
	```ts
		a(path);
		b(path);
	```
- `a` `lock`s on the path, which adds the lock
- `b` tries to `lock` on the path, though it must wait for `a` to finish (in `LockedFS.lock`)
- `a` performs its operations
- `a`'s scope is left, `MutexLock[Symbol.dispose]` runs, unlocking the path
- `b` then performs its operations
-  `b`'s scope is left, `MutexLock[Symbol.dispose]` runs, unlocking the path

I think https://github.com/zen-fs/core/commit/e3878895f107ed43e412b226f4feab6232123a54 may fix something since now the promise won't resolve until the lock is actually cleared.

2024-09-07 04:56 UTC, terryluan12 commented
No worries at all, thanks for allowing me to help! 

I think there's been a misunderstanding. To clarify, the issue occurs in the following scenario, when there are 3 locks; for example A, B, and C. 
In this case, if A locks first, and then B and C lock (in any order), then both B and C are now waiting on A's lock to release. 

When A then releases, both B and C start again at the same time. I believe this is the unintended behaviour, where they both start again at the same time.

2024-09-07 17:10 UTC, james-pre commented
Ah, this makes more sense now! Thanks for the clarification.

Maybe we could look at a wrap and replace, so when B attempts the lock, it replaces the current lock with one that resolves when B is done. This wouldn't impact A since it holds the lock, and doesn't update the reference (i.e. the A's `MutexLock[Symbol.dipose]` resolves only the lock for A).

2024-09-27 21:34 UTC, james-pre commented
@terryluan12 Now that the mutex issue has been solved, can I close this PR?

2024-09-27 22:13 UTC, terryluan12 commented
Yep, absolutely!

2024-09-27 22:13 UTC, closed without merging